default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: <%= ENV['POSTGRES_PASS'] %>
  pool: 5
  
development:
  <<: *default
  database: turninggreen_dev

test:
  <<: *default
  database: turninggreen_test

  
